//
// Created by Maxim Bordyugov on 22/06/2021.
//

#ifndef ROMAN_NUMERALS_PATTERNVISITOR_NODEVISITOR_H_
#define ROMAN_NUMERALS_PATTERNVISITOR_NODEVISITOR_H_

class NodeVisitor {

};

#endif //ROMAN_NUMERALS_PATTERNVISITOR_NODEVISITOR_H_
